import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { MiniDrawer } from "./drawer";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <header>
      <link rel="icon" href="https://i.ibb.co/k5Nn1Yx/Whats-App-Image-2023-06-18-at-11-50-49-PM.jpg" sizes="any" />
      </header>
      <body className={inter.className}>
        <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
        <MiniDrawer  children={children}/>
+           </ThemeProvider>
          
            {/* {children} */}

        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
